datadir: /home/erigon/.local/share/erigon
chain: xlayer-testnet
http: true
private.api.addr: localhost:9091
zkevm.l2-chain-id: 195
zkevm.l2-sequencer-rpc-url:
zkevm.l2-datastreamer-url:
zkevm.l1-chain-id: 11155111
zkevm.l1-rpc-url: http://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662

zkevm.address-sequencer: "0x4820E45eB6Cf99074389544F83FE1F30084bdAb7"
zkevm.address-zkevm: "0x12e9cF0110B6C0EE11534754774253574838E9BD"
zkevm.address-admin: "0x93836f3D8424983BB49BFBca2E9b2bb92B5D8e46"
zkevm.address-rollup: "0x12e9cF0110B6C0EE11534754774253574838E9BD"
zkevm.address-ger-manager: "0x876B4445aDb20FcafacB07179eACB440Cd0cBD81"

zkevm.l1-rollup-id: 1
zkevm.l1-first-block: 5806661
zkevm.l1-block-range: 100
zkevm.l1-query-delay: 6000
zkevm.rpc-ratelimit: 250
zkevm.datastream-version: 2

zkevm.executor-urls: 127.0.0.1:50071
zkevm.sequencer-initial-fork-id: 9
zkevm.data-stream-host: "localhost"
zkevm.data-stream-port: 6900

externalcl: true
http.api: [eth, debug, net, trace, web3, erigon, zkevm]
http.addr: 0.0.0.0
http.port: 8545
