datadir: /Volumes/workspace/data-xlayer/
chain: xlayer-testnet
http: true
private.api.addr: localhost:9091
zkevm.l2-chain-id: 195
zkevm.l2-sequencer-rpc-url: https://testrpc.xlayer.tech
zkevm.l2-datastreamer-url: teststream.xlayer.tech:8800
zkevm.l1-chain-id: 11155111
#zkevm.l1-rpc-url: https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662,https://rpc.ankr.com/eth_sepolia/c3f984153cc537d91e4ab0e18388e42667c0b45b5abfe27b5c612aa18023d9ba,https://rpc.ankr.com/eth_sepolia/daaca8f0fed07b9105dcef0a0ee7abbf1391d8a650dbf8308e4ec136d72d2ea0,https://sepolia.infura.io/v3/fbd1e25856e6411bac0f9093979e2563

#zkevm.l1-rpc-url: https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662
zkevm.l1-rpc-url: https://sepolia.infura.io/v3/bb410aa66f77424ab0260937600de8a5,https://sepolia.infura.io/v3/0d081e04621c4c69b12649fbb63ef18a,https://sepolia.infura.io/v3/fbd1e25856e6411bac0f9093979e2563,https://sepolia.infura.io/v3/563f6332bff84704b14989b8b74e14c0

zkevm.address-sequencer: "0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6"
zkevm.address-zkevm: "0x01469dACfDDA885D68Ff0f8628F2629c14F95a20"
zkevm.address-admin: "0xC432168eF74A83c6E6C76f2c1b42F875E1A223CD"
zkevm.address-rollup: "0x6662621411A8DACC3cA7049C8BddABaa9a999ce3"
zkevm.address-ger-manager: "0x66E61bA00F58b857A9DD2C500F3aBc424A46BD20"

zkevm.l1-rollup-id: 1
zkevm.l1-first-block: 4648290
zkevm.l1-block-range: 2000
zkevm.l1-query-delay: 1000
zkevm.rpc-ratelimit: 250
zkevm.datastream-version: 3

externalcl: true
http.api: [eth, debug, net, trace, web3, erigon, zkevm]
http.addr: 0.0.0.0
http.port: 8545

#zkevm.l2-fork9-upgrade-batch: 476000
zkevm.data-stream-port: 6900
zkevm.data-stream-host: localhost
zkevm.executor-strict: false
zkevm.da-url: http://103.115.40.98:8444

pprof: true
pprof.port: 6060
pprof.addr: 127.0.0.1
zkevm.l1-cache-enabled: true
#zkevm.datastream-new-block-timeout: 30s