name: Resequence test
on:
  push:
    branches:
      - zkevm
      - stable*
  pull_request:
    branches:
      - zkevm
      - stable*
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  resequence-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cdk-erigon
        uses: actions/checkout@v4
        with:
          path: cdk-erigon

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
          repository: 0xPolygon/kurtosis-cdk
          ref: v0.2.12
          path: kurtosis-cdk

      - name: Install Kurtosis CDK tools
        uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          /usr/local/bin/yq --version
      - name: Install polycli
        run: |
          tmp_dir=$(mktemp -d) && curl -L https://github.com/0xPolygon/polygon-cli/releases/download/v0.1.48/polycli_v0.1.48_linux_amd64.tar.gz | tar -xz -C "$tmp_dir" && mv "$tmp_dir"/* /usr/local/bin/polycli && rm -rf "$tmp_dir"
          sudo chmod +x /usr/local/bin/polycli
          /usr/local/bin/polycli version
      - name: Build docker image
        working-directory: ./cdk-erigon
        run: docker build -t cdk-erigon:local --file Dockerfile .

      - name: Remove unused flags
        working-directory: ./kurtosis-cdk
        run: |
          sed -i '/zkevm.sequencer-batch-seal-time:/d' templates/cdk-erigon/config.yml
          sed -i '/zkevm.sequencer-non-empty-batch-seal-time:/d' templates/cdk-erigon/config.yml
          sed -i '/sentry.drop-useless-peers:/d' templates/cdk-erigon/config.yml
          sed -i '/zkevm.pool-manager-url/d' templates/cdk-erigon/config.yml
          sed -i '/zkevm.l2-datastreamer-timeout:/d' templates/cdk-erigon/config.yml
      - name: Configure Kurtosis CDK
        working-directory: ./kurtosis-cdk
        run: |
          /usr/local/bin/yq -i '.args.cdk_erigon_node_image = "cdk-erigon:local"' params.yml
      - name: Deploy Kurtosis CDK package
        working-directory: ./kurtosis-cdk
        run: kurtosis run --enclave cdk-v1 --args-file params.yml --image-download always .

      - name: Test resequence
        working-directory: ./cdk-erigon
        run: .github/scripts/test_resequence.sh
          
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: evm-rpc-tests-logs-${{ github.run_id }}
          path: ./cdk-erigon/logs/evm-rpc-tests.log

      - name: Prepare logs
        working-directory: ./kurtosis-cdk
        if: failure()
        run: |
          mkdir -p ci_logs
          cd ci_logs
          kurtosis service logs cdk-v1 cdk-erigon-node-001 --all > cdk-erigon-node-001.log
          kurtosis service logs cdk-v1 cdk-erigon-sequencer-001 --all > cdk-erigon-sequencer-001.log
          kurtosis service logs cdk-v1 zkevm-agglayer-001 --all > zkevm-agglayer-001.log
          kurtosis service logs cdk-v1 zkevm-prover-001 --all > zkevm-prover-001.log
          kurtosis service logs cdk-v1 cdk-node-001 --all > cdk-node-001.log
          kurtosis service logs cdk-v1 zkevm-bridge-service-001 --all > zkevm-bridge-service-001.log
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs_${{ github.run_id }}
          path: ./kurtosis-cdk/ci_logs